### PR TITLE
Event-based reader

### PR DESCRIPTION
**Pull request by sathorn6**
I'm not very familiar with C++, so i have no idea if this is a good way to do it.
It works like this:

```
PacketReader parser;
parser.on<AbilityLevel>([] (const AbilityLevel& level) { ... });
parser.on<ExpGain>([] (const ExpGain& exp) { ... });
parser.read(some_block);
```

### CODE REVIEW

**Comment by toulouse** [comment]
Hmm. I think we wanted to avoid templates, to make the eventual bridging to C more clearly defined / explicit. Still looking...

**Comment by toulouse** [comment]
Hmm. I don't think it's bad, but with lambdas and stuff I think it'd be better as a library extra rather than part of the core. The underlying pattern makes sense, in that we basically want event subscriptions.

An API that won't be too hard to port to C or other languages is important. What do you think?

**Comment by sathorn6** [comment]
Well, i have no idea how to do events in C. How should it look like?

**Comment by toulouse** [comment]
Hmm. That's a tough question. I imagine it would involve registering a C callback function to receive each block/packet, along with a context variable (probably a struct?) carrying information on the block/packet. Perhaps also with an enum denoting what type it is so a switch can be implemented in the callback to call out to whatever functions are needed.

**Comment by sathorn6** [comment]
Ok, next attempt.
- Parsing is now `Packet parse(Block b)`
- Packets now contain their body in a JSON-like data structure, which can theoretically be used from C (I think)
- It could also be easily converted to e.g. a v8 object for the node binding

Good idea?
I have only implemented it with the AbilityLevel packet for now

**Comment by sathorn6** [comment]
If no one says it's bad, then it's probably not too bad.

**Comment by toulouse** [comment]
I've been sick. I'll take a look tonight.

**Comment by toulouse** [comment]
Hmm. I don't like this, since it's a bit too dynamic for my tastes, but you did the significant legwork to implement it, so it deserves to go in. Unless I'm misreading (I only skimmed), creating a lot of STL data structures or creating instances with `new` seems liable to spam the heap with objects where the stack will do.

**Comment by sathorn6** [comment]
Every `Value` carries its data around as a pointer to the heap because it doesn't know the size of the data (in advance). So i'm not sure how this could be improved with the current scheme, but i don't believe it will cause trouble.

**Pull request merged**
